import smtplib
import os
import markdown
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header
import config.settings as config

def send_report_email(report_path):
    """Sends the generated markdown report via Gmail SMTP as a styled HTML email."""
    if not os.path.exists(report_path):
        print(f"!!! Mail Error: Report file not found at {report_path}")
        return

    print(f">>> Attempting to send report via Email to {config.RECEIVER_EMAILS}...")

    # Read report content
    try:
        with open(report_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"!!! Mail Error: Failed to read report: {e}")
        return

    # Create Message
    message = MIMEMultipart("alternative")
    
    # Extract only the date from filename (e.g., Global_Digest_2026-02-26.md -> 2026-02-26)
    import re
    filename = os.path.basename(report_path)
    date_match = re.search(r'\d{4}-\d{2}-\d{2}', filename)
    report_tag = date_match.group(0) if date_match else filename.replace(".md", "")
    
    subject_title = f"News Digest & Market Insight _ {report_tag}"
    message['Subject'] = Header(subject_title, 'utf-8')
    message['From'] = config.SENDER_EMAIL
    message['To'] = ", ".join(config.RECEIVER_EMAILS)

    # 1. Plain Text version (fallback)
    text_part = MIMEText(content, 'plain', 'utf-8')
    message.attach(text_part)

    # 2. HTML version with Premium CSS Styling
    html_content = markdown.markdown(content, extensions=['tables', 'fenced_code'])
    
    styled_html = f"""
    <html>
    <head>
    <style>
        body {{ font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1a73e8; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        h2 {{ color: #202124; margin-top: 30px; border-left: 4px solid #1a73e8; padding-left: 10px; }}
        h3 {{ color: #444; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        th {{ background-color: #f8f9fa; color: #5f6368; font-weight: bold; border: 1px solid #dee2e6; padding: 12px; text-align: left; }}
        td {{ border: 1px solid #dee2e6; padding: 12px; }}
        tr:nth-child(even) {{ background-color: #fcfcfc; }}
        blockquote {{ margin: 20px 0; padding: 10px 20px; border-left: 5px solid #1a73e8; background: #f0f7ff; color: #555; }}
        code {{ background-color: #f4f4f4; padding: 2px 4px; border-radius: 4px; font-family: 'Courier New', monospace; }}
        .footer {{ margin-top: 40px; border-top: 1px solid #eee; padding-top: 20px; font-size: 12px; color: #888; text-align: center; }}
    </style>
    </head>
    <body>
        {html_content}
        <div class="footer">
            Generated by AI Market Analyst | Data retrieved at {os.path.basename(report_path).split('_')[0] if '_' in report_path else 'today'}
        </div>
    </body>
    </html>
    """
    html_part = MIMEText(styled_html, 'html', 'utf-8')
    message.attach(html_part)

    try:
        # Connect to Gmail SMTP (SSL)
        server = smtplib.SMTP_SSL(config.SMTP_SERVER, config.SMTP_PORT)
        server.login(config.SENDER_EMAIL, config.SENDER_PASSWORD)
        server.sendmail(config.SENDER_EMAIL, config.RECEIVER_EMAILS, message.as_string())
        server.quit()
        print(f">>> Success: Professional Styled Report sent to {len(config.RECEIVER_EMAILS)} recipients.")
    except Exception as e:
        print(f"!!! SMTP Error: {e}")
        print("Tip: Make sure you used a 16-digit 'App Password' and not your main account password.")
